from .PainterAudioLength import NODE_CLASS_MAPPINGS as AUDIO_LENGTH_CLASS_MAPPINGS
from .PainterAudioLength import NODE_DISPLAY_NAME_MAPPINGS as AUDIO_LENGTH_DISPLAY_MAPPINGS
from .PainterAudioCut import NODE_CLASS_MAPPINGS as AUDIO_CUT_CLASS_MAPPINGS
from .PainterAudioCut import NODE_DISPLAY_NAME_MAPPINGS as AUDIO_CUT_DISPLAY_MAPPINGS

NODE_CLASS_MAPPINGS = {
    **AUDIO_LENGTH_CLASS_MAPPINGS,
    **AUDIO_CUT_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **AUDIO_LENGTH_DISPLAY_MAPPINGS,
    **AUDIO_CUT_DISPLAY_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
